version: "3.3"
name: warandinga-hub
services:
  warandinga-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  warandinga-db-interface:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
     - warandinga-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@warandinga-db:27017/
volumes:
  mongo-data:
